.SH NAME
SSH Alias Manager (sam)
.SH DESCRIPTION
Manages SSH aliases in ~/.ssh/config
.SH OPTIONS
  sam help
  sam ls                                 List all SSH aliases (with index)
  sam add [options]                      Add SSH alias (interactive or CLI)
     [ -h HOST/IP ] [ -u USER ] [ -i KEY ] [ -a ALIAS ]
  sam remove -a ALIAS                    Remove SSH alias (by alias or index)
  sam edit -a ALIAS                      Edit SSH alias (interactive; alias or index)
  sam ssh <index>                        SSH into server by its index in the list
Options also available as: --add, --remove, --edit, --ls, --help
Environment:
  SAM_CONFIG   Path to primary SSH config (default: ~/.ssh/config)
