.TH SAM 1 "May 2025" "SSH Alias Manager"
.SH NAME
sam \- SSH Alias Manager
.SH SYNOPSIS
sam [OPTIONS]
.SH DESCRIPTION
Manages SSH aliases in ~/.ssh/config
.SH OPTIONS
--help         Show help
-ls            List aliases
--add          Add a new alias
--remove       Remove an alias
--edit         Edit an alias
